config/routes.rb
Rails.application.routes.draw do
  resources :portfolios, only: [:new, :create, :index, :destroy, :show, :update, :edit] do
    resources :positions, except: [:show, :index] #mpf - I don't think we need all of the actions for portfolios, doesn't hurt anything at this point through
  end

  devise_for :users

  devise_scope :user do
  	root :to => 'devise/sessions#new'
	end

	resources :stocks, except: [:show, :index, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  validates :portfolio_name, presence: true

  belongs_to :user
  has_many :positions
  has_many :stocks, through: :positions

  def total_value
    value = 0
    positions.each do |position|
       value += (position.stock.current_price.to_f * position.owned_shares)
    end
    value.to_f
  end

  def original_value
    value = 0
    positions.each do |position|
      value += (position.purchase_price * position.owned_shares)
    end
    value.to_f
  end

  def total_pnl
    total_value - original_value
  end

  def percent_change
    (total_value - original_value) / original_value * 100
  end

  def css_green_or_red
    if total_pnl >= 0
      "green-money"
    elsif total_pnl < 0
      "red-money"
    end
  end

end

app/models/position.rb
class Position < ApplicationRecord
	belongs_to :stock
	belongs_to :portfolio

  validates_presence_of :owned_shares, :purchase_price, :portfolio_id, :stock_id

  def profit_loss
    self.stock.current_price.to_d - self.purchase_price.to_d
  end

  def percent_change
    (self.stock.current_price.to_d - self.purchase_price) / self.purchase_price * 100
  end
end

app/models/stock.rb
class Stock < ApplicationRecord
	has_many :positions
	has_many :portfolios, through: :positions

	validates_presence_of :name, :symbol
	validates_uniqueness_of :name, :symbol

	def current_price
		response = current_price_request
		if response.has_key?("Error Message")
			return false
		else
			response["Time Series (1min)"].first[1]["4. close"]
		end
	end

	def is_stock_already_persisted
		if Stock.find_by(symbol: self.symbol).instance_of? Stock
			return Stock.find_by(symbol: self.symbol)
		elsif Stock.find_by(name: self.name).instance_of? Stock
			return Stock.find_by(name: self.name)
		else
			return false
		end
	end

	private
		def current_price_request
			uri = URI.parse("https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=#{self.symbol}&interval=1min&apikey=#{ENV["ALPHA_VANTAGE_KEY"]}")
			request = Net::HTTP.get(uri)
			JSON.parse(request)
		end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :portfolios
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(devise)
  	portfolios_path
	end

  def bounce_non_user
    redirect_to 'www.google.com' if !current_user
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  def index
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    bounce_non_user
    @portfolio = Portfolio.new(portfolio_params)
    current_user.portfolios << @portfolio
    if @portfolio.save
    	flash[:notice] = "Portfolio added successfully"
      redirect_to @portfolio
    else
      render :new, status: 422
    end
  end

  def edit
  end

  def update
  end

  def show
    @portfolio = Portfolio.find(params[:id])
    @positions = @portfolio.positions
  end

  def index
    @portfolios = Portfolio.all
  end

  def destroy
    portfolio = Portfolio.find(params[:id])
    portfolio.destroy
    redirect_to portfolios_path
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:portfolio_name)
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  def new
    @position = Position.new
    @stock = Stock.new
  end

  def create
    @stock = Stock.new(name: params[:position][:name], symbol: params[:position][:symbol].upcase)
    @position = Position.new(position_params)
    if !@stock.current_price
    	flash[:notice] = "Invalid stock symbol"
    	render 'new'
      return
    else
	    if !@stock.is_stock_already_persisted
	      @stock.save
	      @position.stock_id = @stock.id
	    else
	      @wanted_stock = @stock.is_stock_already_persisted
	      @position.stock_id = @wanted_stock.id
	    end
	  end
    @position.portfolio_id = params[:portfolio_id]
    if @position.save
    	flash[:notice] = "Position added successfully"
      redirect_to @position.portfolio
    else
      render 'new'
    end
  end

  def edit
    @position = Position.find(params[:id])
    @stock = Stock.find(@position.stock_id)
  end

  def update
    @position = Position.find(params[:id])

    if @position.update(position_params)
      redirect_to @position.portfolio
    else
      render 'edit'
    end
  end

  def destroy
    @position = Position.find(params[:id])
    @position.destroy
    redirect_to @position.portfolio
  end

  private
    def position_params
      params.require(:position).permit(:owned_shares, :purchase_price)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
	def new
		@stock = Stock.new
	end

	def create
		@stock = Stock.new(stock_params)
		@stock.symbol.upcase!
		if @stock.is_stock_already_persisted
			status 406
			flash[:notice] = "Stock already exists"
			render 'new'
		else
			if !@stock.current_price
				flash[:notice] = "Stock symbol is invalid"
				render 'new'
			else
				if @stock.save
					flash[:notice] = "Stock added successfully"
					redirect_to portfolios_path
				else
					@errors = @stock.errors.full_messages
					render 'new'
				end
			end
		end
	end

	def edit
		@stock = Stock.find_by(id: params[:id])
		if request.xhr?
			render :json => { page: render_to_string('stocks/edit', layout: false, locals: { stock: @stock }) }
		else
			render 'edit'
		end
	end

	def update
		@stock = Stock.find_by(id: params[:id])
		@stock.update_attributes(stock_params)
		@stock.symbol.upcase!
		if !@stock.current_price
			flash[:notice] = "Stock symbol is invalid"
			render 'edit'
		else
			if @stock.save
				flash[:notice] = "Stock updated successfully"
				redirect_to portfolios_path
			else
				@errors = @stock.errors.full_messages
				render 'edit'
			end
		end
	end

	private
		def stock_params
			params.require(:stock).permit(:name, :symbol)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioTracker</title>
    <%= stylesheet_link_tag "application.css" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= stylesheet_link_tag "application.css" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "markscript" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="navbar">
      <%= render "navbar" %>
    </div>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/portfolios/_edit_new_form.html.erb
<%= form_with model: @portfolio, url: portfolios_path do |f|%>
	<%= f.label :portfolio_name, "Portfolio Name:" %><br>
  <%= f.text_field :portfolio_name %>
  <%= f.submit "Submit" %>
<% end %>

app/views/portfolios/_navbar.html.erb
	<% if user_signed_in? %>
		<%= link_to 'Home', portfolios_path %> | 
	  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>        
	<% else %>
	  <%= link_to 'Login', new_user_session_path %>  
	<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit Portfolio</h1>

<%= render "edit_new_form"  %>

app/views/portfolios/index.html.erb
<div id="portfolio-index-title"><h1>Portfolio Index</h1></div>

<div id="portfolio-link"> <%= link_to("New Portfolio", new_portfolio_path) %><br> </div>


<% if @portfolios %>
  <% @portfolios.each do |portfolio| %>
    <div class="individual-portfolio">
      <p class="portfolio-text"><%= link_to(portfolio.portfolio_name, portfolio_path(portfolio)) %>

        <span id="portfolio-numbers" class=<%=portfolio.css_green_or_red%>>
            <%= number_to_currency(portfolio.total_pnl) %>
            <% if portfolio == nil || portfolio.total_pnl == 0 %>
              (0.00%)
            <% else %>
              (<%= number_to_percentage(portfolio.percent_change, precision: 2) %>)
            <% end %>
        </span>

        <%= button_to "Delete Portfolio", portfolio_path(portfolio),method: :delete, data: { confirm: "Are you sure?" }, class: "delete-portfolio" %>
      </p>
    </div>
  <% end %>
<% end %>

<h2 id="total-total">
  Total:
  <% if @portfolios.any? %>
    <% total = [] %>
    <% @portfolios.each do |portfolio| %>
      <% total << portfolio.total_pnl %>
    <% end %>
    <%= number_to_currency(total.inject(:+)) %>
  <% else %>
    $0.00
  <% end %>
</h2>

app/views/portfolios/new.html.erb
<h1>Create New Portfolio</h1>
<% if @errors %>
	<%= @portfolio.errors.full_messages %>
<% end %>

<%= render "edit_new_form"  %>

app/views/portfolios/show.html.erb
<h2><%= @portfolio.portfolio_name %></h2>
<div>
  Total Profit/Loss
</div>
<h1 class="notopmarg <%= @portfolio.css_green_or_red %>">
  <%= number_to_currency(@portfolio.total_pnl) %>
  <% if @portfolio.total_pnl == 0 %>
    (0.00%)
  <% else %>
    (<%= number_to_percentage(@portfolio.percent_change, precision: 2) %>)
  <% end %>
</h1>

<div class="colhead p-stock-name">
  Name
</div>
<div class="colhead p-stock-symbol">
  Sym
</div>
<div class="colhead p-stock-purchase">
  Purchase
</div>
<div class="colhead p-stock-current">
  Current
</div>
<div class="colhead p-stock-profit-loss">
  P/L
</div>
<br><br>

<%= render partial: 'positions/position', collection: @portfolio.positions %>

<%= link_to("Add New Position", new_portfolio_position_path(@portfolio)) %>

app/views/positions/_navbar.html.erb
<% if user_signed_in? %>
	<%= link_to 'Home', portfolios_path %> | 
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>        
<% else %>
  <%= link_to 'Login', new_user_session_path %>  
<% end %>

app/views/positions/_position.html.erb
<div class="total-position-row">
  <div class="p-stock-name">
    <%= position.stock.name %>
  </div>
  <div class="p-stock-symbol">
    <%= position.stock.symbol %>
  </div>
  <div class="p-stock-purchase">
    <%= number_to_currency(position.purchase_price) %>
  </div>
  <div class="p-stock-current">
    <%= number_to_currency(position.stock.current_price.to_f) %>
  </div>
  <div class="p-stock-profit-loss">
    <%= number_to_currency(position.profit_loss.to_f) %> (<%= number_to_percentage(position.percent_change, precision: 2) %>)
  </div>
  <div class="edit-delete-links-container">
    <div class="edit-links">
      <%= link_to("Edit Stock", edit_stock_path(position.stock), class: :link_edit_stock) %> |
      <%= link_to("Edit Position", edit_portfolio_position_path(@portfolio, position), class: :link_edit_position) %> |
    </div>
    <div class="delete-button">
      <%= button_to "Delete", portfolio_position_path(@portfolio, position), method: :delete %>
    </div>
  </div>

</div>
<br>

app/views/positions/_show.html.erb
<div class="total-position-row">
  <div class="p-stock-name">
    <%= position.stock.name %>
  </div>
  <div class="p-stock-symbol">
    <%= position.stock.symbol %>
  </div>
  <div class="p-stock-purchase">
    <%= position.purchase_price %>
  </div>
  <div class="p-stock-current">
    <%= position.stock.current_price %>
  </div>
  <div class="p-stock-profit-loss">
    <%= position.profit_loss %>
  </div>
</div>

app/views/positions/_show_individual.html.erb
<div>
  <div>
    <%= position.stock.name %>
  </div>
  <div>
    <%= position.stock.symbol %>
  </div>
  <div>
    <%= position.purchase_price %>
  </div>
  <div>
    <%= position.stock.current_price %>
  </div>
  <div>
    <%= position.profit_loss %>
  </div>
</div>

app/views/positions/edit.html.erb
<h1>Edit Position</h1>

<%= form_with model: @position, url: portfolio_position_path, id: :update_position_form do |f| %>

  <% if @position.errors.any? %>
    You have <%= pluralize(@position.errors.count, 'error') %>
    <%= @position.errors.full_messages.each do |message|%>
      <%= message %>
    <% end %>
  <% end %>

  <p>
    <%= f.label :owned_shares, id: :label_owned_shares %><br>
    <%= f.text_field :owned_shares, id: :owned_shares %>
  </p>
  <p>
    <%= f.label :purchase_price, id: :label_purchase_price %><br>
    <%= f.text_field :purchase_price, id: :purchase_price %>
  </p>
  <p>
    <%= f.label :sale_price, id: :label_sale_price %><br>
    <%= f.text_field :sale_price, id: :sale_price %>
  </p>
  <p>
    <%= f.submit "Update Position", id: :submit_position_update %>
  </p>

<% end %>

app/views/positions/new.html.erb
<h1>Create New Position</h1>

<%= form_with model: @position, url: portfolio_positions_path do |f| %>

  <% if @position.errors.any? %>
    You have <%= pluralize(@position.errors.count, 'error') %>
    <%= @position.errors.full_messages.each do |message|%>
      <%= message %>
    <% end %>
  <% end %>

  <p>
    <%= f.label :owned_shares %><br>
    <%= f.text_field :owned_shares %>
  </p>
  <p>
    <%= f.label :purchase_price %><br>
    <%= f.text_field :purchase_price %>
  </p>
    <%= f.fields_for :stock do |sf| %>
    <p>
      <%= f.label :stock_name %><br>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :stock_symbol %><br>
      <%= f.text_field :symbol %>
    </p>
    <% end %>
  <p>
    <%= f.submit "Add Position" %>
  </p>

<% end %>

app/views/stocks/_form.html.erb
<%= form_with model: @stock, id: :stock_form do |f| %>
	<%= f.label :name, id: :label_stock_name %>
	<%= f.text_field :name, id: :stock_name %>
	<%= f.label :symbol, id: :label_stock_symbol %>
	<%= f.text_field :symbol, id: :stock_symbol %>
	<%= f.submit 'Save', id: :stock_submit %>
<% end %>

app/views/stocks/edit.html.erb
<div id="edit-stock-div">
<h2 id="edit-stock-heading">Edit Stock</h2>

<%= render 'form' %>
</div>

app/views/stocks/new.html.erb
<h2 id="new-stock-heading">New Stock</h2>

<%= render 'form' %>